server:
  servlet:
    context-path: /
  undertow:
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

spring:
  profiles:
    active: @profile.active@
  application:
    name: @artifactId@
  main:
    allow-bean-definition-overriding: true
  aop:
    proxy-target-class: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,info
  endpoint:
    health:
      show-details: always

info:
  name: @artifactId@
  description: @description@
  version: @version@

logging:
  config: classpath:logback-spring.xml

springdoc:
  show-actuator: true
  use-management-port: false
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  group-configs:
    - group: 'base'
      paths-to-match: '/**'
      packages-to-scan: com.tml.**.controller

#swagger
knife4j:
  #开启增强配置
  enable: true
  #开启生产环境屏蔽
  production: true
  basic:
    enable: true
    username: admin
    password: Bright@2025

bright:
  # swagger配置
  swagger2:
    enabled: true
    description: @description@
    title: @artifactId@
    version: @version@

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true